name: Compile AHK Script to EXE

on:
  workflow_dispatch: # Only triggers manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Compile the AHK script to EXE using 64-bit AutoHotkey binary
      - name: Compile AHK script to EXE (64-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Compile using the local ahk2exe.exe from the repository with 64-bit binary
          & ".\ahk2exe\ahk2exe.exe" /in .\code\Blower.ahk /out output_64bit.exe /bin .\ahk2exe\AutoHotkey64.exe

      # Compile the AHK script to EXE using 32-bit AutoHotkey binary
      - name: Compile AHK script to EXE (32-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force

          # Compile using the local ahk2exe.exe from the repository with 32-bit binary
          & ".\ahk2exe\ahk2exe.exe" /in .\code\Blower.ahk /out output_32bit.exe /bin .\ahk2exe\AutoHotkey.exe

      # Upload the 64-bit EXE as an artifact
      - name: Upload compiled 64-bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: compiled-64bit-ahk-exe
          path: output_64bit.exe

      # Upload the 32-bit EXE as an artifact
      - name: Upload compiled 32-bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: compiled-32bit-ahk-exe
          path: output_32bit.exe
