name: Compile AHK Script to EXE

on:
  workflow_dispatch: # Only triggers manually

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Compile the AHK script to EXE using 64-bit AutoHotkey binary
      - name: Compile AHK script to EXE (64-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Compile using the local ahk2exe.exe from the repository with 64-bit binary
          & D:\a\LeafBlower\LeafBlower\Ahk2Exe\ahk2exe.exe /in ".\code\Blower.ahk" /out "D:\a\LeafBlower\LeafBlower\Leaf.Blower.x64.exe" /bin ".\ahk2exe\AutoHotkey64.exe" /icon "D:\a\LeafBlower\LeafBlower/Icons/Platinum_Leaf.ico"

      # Compile the AHK script to EXE using 32-bit AutoHotkey binary
      - name: Compile AHK script to EXE (32-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force

          # Compile using the local ahk2exe.exe from the repository with 32-bit binary
          & D:\a\LeafBlower\LeafBlower\Ahk2Exe\ahk2exe.exe /in ".\code\Blower.ahk" /out "D:\a\LeafBlower\LeafBlower\Leaf.Blower.x86.exe" /bin ".\ahk2exe\AutoHotkey32.exe" /icon "D:\a\LeafBlower\LeafBlower/Icons/Platinum_Leaf.ico"

      - name: Create a Draft
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest --generate-notes --title "Leaf Blower" --draft

      - name: Get latest draft release tag
        id: get_draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $LATEST_DRAFT = gh release list --limit 1 --json tagName,isDraft --jq ".[] | select(.isDraft) | .tagName"
          if (-not $LATEST_DRAFT) {
            Write-Host "No draft release found."
            exit 1
          }
          Write-Host "Latest draft release: $LATEST_DRAFT"
          echo "tag_name=$LATEST_DRAFT" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
                                                      
      - name: List directory contents (Windows)
        run: dir -s

      - name: Upload asset to latest draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$env:tag_name" D:\a\LeafBlower\LeafBlower\Leaf.Blower.x86.exe
        shell: pwsh
                                                                                        
