name: Compile AHK Script to EXE

on:
  workflow_dispatch: # Only triggers manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # List files to ensure the correct paths
      - name: List files in repository
        run: |
          echo "Listing files in the repository..."
          Get-ChildItem -Recurse

      # Install AutoHotkey using Chocolatey
      - name: Install AutoHotkey
        run: |
          echo "Installing AutoHotkey using Chocolatey..."
          choco install autohotkey -y

      # Find the path of ahk2exe (search in typical locations)
      - name: Find ahk2exe
        run: |
          $ahk2exePath = Get-Command ahk2exe -ErrorAction SilentlyContinue
          if ($ahk2exePath) {
            echo "Found ahk2exe at $ahk2exePath"
          } else {
            echo "Error: ahk2exe not found."
            exit 1
          }

      # Compile the AHK script to EXE using the found ahk2exe
      - name: Compile AHK script to EXE
        run: |
          echo "Starting compilation of Blower.ahk..."
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Path to the AHK script
          $scriptPath = ".\code\Blower.ahk"
          $outputPath = ".\output.exe"

          # Run ahk2exe using the found path
          $ahk2exeResult = & $ahk2exePath /in $scriptPath /out $outputPath /compile 2>&1
          echo "ahk2exe output: $ahk2exeResult"

      # List the files after the compilation attempt
      - name: List generated files
        run: |
          echo "Listing all files after compilation attempt..."
          Get-ChildItem -Recurse

      # Check if the EXE was created
      - name: Check if EXE was created
        run: |
          if (Test-Path -Path ".\output.exe") {
            echo "EXE file created successfully!"
          } else {
            echo "EXE file not created. Please check for errors."
            exit 1
          }

      # Upload the EXE as an artifact using the correct version
      - name: Upload compiled EXE
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ahk-exe
          path: .\output.exe
