name: Compile AHK Script to EXE

on:
  workflow_dispatch: # Only triggers manually

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Compile the AHK script to EXE using 64-bit AutoHotkey binary
      - name: Compile AHK script to EXE (64-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Compile using the local ahk2exe.exe from the repository with 64-bit binary
          & ".\ahk2exe\ahk2exe.exe" /in .\code\Blower.ahk /out Leaf.Blower.x64.exe /bin .\ahk2exe\AutoHotkey64.exe /icon ./Icons/Platinum_Leaf.ico 

      # Compile the AHK script to EXE using 32-bit AutoHotkey binary
      - name: Compile AHK script to EXE (32-bit)
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force

          # Compile using the local ahk2exe.exe from the repository with 32-bit binary
          & ".\ahk2exe\ahk2exe.exe" /in .\code\Blower.ahk /out Leaf.Blower.x86.exe /bin .\ahk2exe\AutoHotkey32.exe /icon ./Icons/Platinum_Leaf.ico

      - name: Create a Draft
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest \
            --generate-notes \
            --title "Latest Draft Release" \
            --draft

      # Upload the 64-bit EXE as an artifact
      - name: Upload compiled 64bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: Leaf.Blower.x64.exe
          path: D:\a\LeafBlower\LeafBlower\code


      # Upload the 32-bit EXE as an artifact
      - name: Upload compiled 32bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: Leaf.Blower.x86.exe
          path: D:\a\LeafBlower\LeafBlower\code
