name: Compile AHK Script to EXE

on:
  workflow_dispatch: # Only triggers manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Compile the AHK script to EXE using ahk2exe with command-line arguments
      - name: Compile AHK script to EXE
        run: |
          # Ensure ahk2exe is executable
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Compile using the local ahk2exe.exe with command-line arguments (no output specified)
          & ".\ahk2exe\ahk2exe.exe" /in .\code\Blower.ahk

      # Upload the EXE as an artifact
      - name: Upload compiled EXE
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ahk-exe
          path: .\Blower.exe
